domain: 127.0.0.1:1000

server:
  port: 1000

# spring config datasource and mail
spring:
  application:
    name: SchoolMangerSpring # application name
  datasource:
    url: ${DB_URL:localhost} # database url
    username: ${DB_USERNAME:username} # database username
    password: ${DB_PASSWORD:password} # database password
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 10
    driver-class-name:
  mail:
    host: smtp.mou.best
    username: forum@mou.best
    password: "*pR@5CFFM9p@#Hq"
  servlet:
    multipart:
      max-file-size: 5MB # max file size

# pebble config
pebble:
  enabled: true
  prefix: templates/
  suffix: .html
  cache: false # cache config, in deploy should is true
  exposeRequestAttributes: true
  expose-session-attributes: true
  greedy-match-method: true # greedy matching mode

# log
logging:
  config: classpath:log4j2.xml
  level:
    root: info
    com.mou.gameforum.controller: info
    com.baomidou.mybatisplus: debug

#mybatis plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl # mybatis plus log config
    map-underscore-to-camel-case: false #  camel case config

# spring doc
springdoc:
  api-docs:
    path: /api-docs
    version: openapi_3_0
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    url: /api-docs
    path: /swagger

# storage config
storage:
  location: files
