server:
  port: 1000

# datasource
spring:
  application:
    name: SchoolMangerSpring
  datasource:
    url: ${DB_URL:localhost} # database url
    username: ${DB_USERNAME:username} # database username
    password: ${DB_PASSWORD:password} # database password
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 10
    driver-class-name: com.mysql.cj.jdbc.Driver

pebble:
  enabled: true
  prefix: templates/
  suffix: .html
  cache: false # cache config, in deploy shoube is true

# log
logging:
  config: classpath:log4j2.xml
  level:
    root: debug
    com.mou.gameforum.controller: debug


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # mybatis plus log config
    map-underscore-to-camel-case: false #  camel case config
